// Mirrors the Prisma enums for admin-side Zod schemas — kept in sync manually.
const LEAD_STATUSES = ["NEW", "IN_REVIEW", "CONVERTED", "CLOSED"];
const RFQ_STATUSES = ["NEW", "IN_PROGRESS", "QUOTED", "NEGOTIATING", "WON", "LOST", "CANCELLED"];
const QUOTATION_STATUSES = ["DRAFT", "SENT", "VIEWED", "ACCEPTED", "REJECTED", "SUPERSEDED"];
const QUOTATION_LINE_TYPES = ["PRODUCT", "SHIPPING", "DISCOUNT", "ADJUSTMENT"];
const STAFF_ROLES = ["ADMIN", "SALES"];

module.exports = { LEAD_STATUSES, RFQ_STATUSES, QUOTATION_STATUSES, QUOTATION_LINE_TYPES, STAFF_ROLES };
