/**
 * New marketplace products (Phase 6A §27-30) — filling the required
 * coverage groups (§28) the T-shirt-heavy legacy DB has nothing for.
 * Every entry uses QUOTE_ONLY pricing: there is no reliable agreed price
 * for any of these (no legacy pricing_slabs row, no exact-match mock
 * pricing already present in the current prototype for this specific
 * product), so per §30 they're priced QUOTE_ONLY rather than inventing
 * numbers. `generated: true` marks every row here for the review report
 * (§32) — there's no schema field for this (deliberately not adding one,
 * per §58), so the distinction lives only in this source file and the
 * generated report.
 *
 * `customizable` is false on every entry here for the same reason it's
 * false on every legacy-imported product (see legacyProductPlan.js): none
 * of these have a real calibrated customization photo or PlacementZone,
 * and §26/§37 are explicit that fabricating either is worse than leaving
 * the flag off until an admin sets one up for real through the Catalogue
 * Admin this phase's predecessor built.
 */
const NEW_PRODUCTS = [
  // ── Hoodies & Sweatshirts ──────────────────────────────────────────────
  {
    slug: "pullover-hoodie",
    name: "Pullover Hoodie",
    category: "hoodies",
    description: "A heavyweight cotton-fleece pullover hoodie for winter merchandise, corporate outerwear and team kits.",
    material: "cotton fleece",
    gsm: 320,
    moq: 10,
    unit: "piece",
    variantType: "size",
    dispatchEstimate: "10–14 working days",
    specifications: [
      { label: "Fabric", value: "Cotton Fleece" },
      { label: "GSM", value: "320 GSM" },
      { label: "Fit", value: "Regular" },
    ],
    tags: ["corporate-teams", "employee-gifting"],
  },
  {
    slug: "zipper-hoodie",
    name: "Zipper Hoodie",
    category: "hoodies",
    description: "A full-zip cotton-fleece hoodie with a kangaroo pocket — a versatile option for branded outerwear.",
    material: "cotton fleece",
    gsm: 320,
    moq: 10,
    unit: "piece",
    variantType: "size",
    dispatchEstimate: "10–14 working days",
    specifications: [
      { label: "Fabric", value: "Cotton Fleece" },
      { label: "GSM", value: "320 GSM" },
      { label: "Closure", value: "Full Zip" },
    ],
    tags: ["corporate-teams", "employee-gifting"],
  },
  // ── Uniforms ─────────────────────────────────────────────────────────
  {
    slug: "corporate-staff-uniform-tshirt",
    name: "Corporate Staff Uniform T-Shirt",
    category: "uniforms",
    description: "A durable poly-cotton uniform T-shirt built for daily staff wear, with consistent sizing across bulk orders.",
    material: "poly-cotton",
    gsm: 180,
    moq: 20,
    unit: "piece",
    variantType: "size",
    dispatchEstimate: "10–14 working days",
    specifications: [
      { label: "Fabric", value: "Poly-Cotton" },
      { label: "GSM", value: "180 GSM" },
    ],
    tags: ["corporate-teams"],
  },
  // ── Caps ─────────────────────────────────────────────────────────────
  {
    slug: "classic-cap",
    name: "Classic Cap",
    category: "caps",
    description: "A structured six-panel cotton-twill cap with an adjustable strap — a straightforward option for logo embroidery.",
    material: "cotton twill",
    gsm: null,
    moq: 50,
    unit: "piece",
    dispatchEstimate: "8–12 working days",
    specifications: [{ label: "Fabric", value: "Cotton Twill" }, { label: "Closure", value: "Adjustable Strap" }],
    tags: ["promotional", "events"],
  },
  {
    slug: "premium-cap",
    name: "Premium Cap",
    category: "caps",
    description: "An unstructured cotton-twill cap with a curved brim and a metal buckle closure for a premium finish.",
    material: "cotton twill",
    gsm: null,
    moq: 50,
    unit: "piece",
    dispatchEstimate: "8–12 working days",
    specifications: [{ label: "Fabric", value: "Cotton Twill" }, { label: "Closure", value: "Metal Buckle" }],
    tags: ["employee-gifting"],
  },
  // ── Bags ─────────────────────────────────────────────────────────────
  {
    slug: "cotton-tote-bag",
    name: "Cotton Tote Bag",
    category: "tote-bags",
    description: "A natural cotton-canvas tote with reinforced handles — an everyday carry option for events and promotions.",
    material: "cotton canvas",
    gsm: null,
    moq: 25,
    unit: "piece",
    dispatchEstimate: "7–10 working days",
    specifications: [{ label: "Material", value: "Cotton Canvas" }],
    tags: ["events", "promotional"],
  },
  {
    slug: "laptop-backpack",
    name: "Laptop Backpack",
    category: "bags",
    description: "A padded polyester laptop backpack with a dedicated device sleeve — a practical welcome-kit and gifting item.",
    material: "polyester",
    gsm: null,
    moq: 25,
    unit: "piece",
    dispatchEstimate: "10–14 working days",
    specifications: [{ label: "Material", value: "Polyester" }, { label: "Compartment", value: "Padded Laptop Sleeve" }],
    tags: ["employee-gifting"],
  },
  {
    slug: "drawstring-bag",
    name: "Drawstring Bag",
    category: "bags",
    description: "A lightweight polyester drawstring bag — a low-cost giveaway option for events and marketing campaigns.",
    material: "polyester",
    gsm: null,
    moq: 50,
    unit: "piece",
    dispatchEstimate: "7–10 working days",
    specifications: [{ label: "Material", value: "Polyester" }],
    tags: ["events", "marketing-campaigns"],
  },
  // ── Drinkware ────────────────────────────────────────────────────────
  {
    slug: "vacuum-insulated-bottle",
    name: "Vacuum Insulated Bottle",
    category: "bottles",
    description: "A double-wall vacuum-insulated stainless steel bottle that keeps drinks hot or cold for extended periods.",
    material: "stainless steel",
    gsm: null,
    moq: 25,
    unit: "piece",
    dispatchEstimate: "8–12 working days",
    specifications: [{ label: "Material", value: "Stainless Steel" }, { label: "Insulation", value: "Double-Wall Vacuum" }],
    tags: ["corporate-teams", "employee-gifting"],
  },
  {
    slug: "sipper-tumbler",
    name: "Sipper / Tumbler",
    category: "tumblers",
    description: "A stainless steel sipper tumbler with a straw lid — a practical daily-use gifting item.",
    material: "stainless steel",
    gsm: null,
    moq: 25,
    unit: "piece",
    dispatchEstimate: "8–12 working days",
    specifications: [{ label: "Material", value: "Stainless Steel" }],
    tags: ["employee-gifting"],
  },
  {
    slug: "ceramic-mug",
    name: "Ceramic Mug",
    category: "mugs",
    description: "A classic ceramic mug suitable for logo printing — a dependable, familiar corporate gifting staple.",
    material: "ceramic",
    gsm: null,
    moq: 25,
    unit: "piece",
    dispatchEstimate: "8–12 working days",
    specifications: [{ label: "Material", value: "Ceramic" }],
    tags: ["employee-gifting", "corporate-teams"],
  },
  // ── Stationery ───────────────────────────────────────────────────────
  {
    slug: "executive-notebook",
    name: "Executive Notebook",
    category: "notebooks",
    description: "A hardbound, leather-finish executive notebook for premium corporate gifting and welcome kits.",
    material: "hardbound leather-finish",
    gsm: null,
    moq: 25,
    unit: "piece",
    dispatchEstimate: "8–12 working days",
    specifications: [{ label: "Binding", value: "Hardbound" }, { label: "Finish", value: "Leather-Finish Cover" }],
    tags: ["employee-gifting", "corporate-teams"],
  },
  {
    slug: "a5-notebook-diary",
    name: "A5 Notebook / Diary",
    category: "notebooks",
    description: "A compact A5 hardbound notebook — a practical, budget-friendly bulk gifting or conference giveaway item.",
    material: "hardbound",
    gsm: null,
    moq: 50,
    unit: "piece",
    dispatchEstimate: "7–10 working days",
    specifications: [{ label: "Size", value: "A5" }, { label: "Binding", value: "Hardbound" }],
    tags: ["events", "marketing-campaigns"],
  },
  {
    slug: "metal-pen",
    name: "Metal Pen",
    category: "pens",
    description: "A metal-body ballpoint pen with a satin finish, suitable for laser engraving — a common executive gifting item.",
    material: "metal",
    gsm: null,
    moq: 100,
    unit: "piece",
    dispatchEstimate: "7–10 working days",
    specifications: [{ label: "Body", value: "Metal" }, { label: "Tip", value: "Ballpoint" }],
    tags: ["employee-gifting", "corporate-teams"],
  },
  {
    slug: "plastic-promotional-pen",
    name: "Plastic Promotional Pen",
    category: "pens",
    description: "A lightweight plastic ballpoint pen for high-volume event and marketing giveaways.",
    material: "plastic",
    gsm: null,
    moq: 200,
    unit: "piece",
    dispatchEstimate: "7–10 working days",
    specifications: [{ label: "Body", value: "Plastic" }, { label: "Tip", value: "Ballpoint" }],
    tags: ["events", "marketing-campaigns", "promotional"],
  },
  // ── Corporate Gifts ──────────────────────────────────────────────────
  {
    // Content basis: legacy "GIFT SET" product description (a notebook +
    // metal pen presentation box) — see legacyProductPlan.js's skip
    // reason for that row. Reused as content, not imported as a T-shirt.
    slug: "executive-gift-set",
    name: "Executive Gift Set",
    category: "corporate-gifts",
    description: "A notebook and metal pen presented together in a branded gift box — a straightforward premium gifting combination for professionals.",
    material: "mixed",
    gsm: null,
    moq: 25,
    unit: "set",
    dispatchEstimate: "10–14 working days",
    specifications: [{ label: "Contents", value: "Notebook + Metal Pen" }, { label: "Packaging", value: "Branded Gift Box" }],
    tags: ["employee-gifting", "corporate-teams"],
  },
  {
    slug: "festival-gift-box",
    name: "Festival Gift Box",
    category: "corporate-gifts",
    description: "A curated festival gifting box — final contents (sweets, dry fruits, desk items) are confirmed with the team before production.",
    material: "mixed",
    gsm: null,
    moq: 25,
    unit: "box",
    dispatchEstimate: "10–14 working days",
    specifications: [{ label: "Packaging", value: "Branded Gift Box" }],
    tags: ["employee-gifting"],
  },
  {
    slug: "conference-kit",
    name: "Conference Kit",
    category: "corporate-gifts",
    description: "A bundled conference welcome kit — typically a bag, notebook and pen — assembled to the event's branding.",
    material: "mixed",
    gsm: null,
    moq: 25,
    unit: "kit",
    dispatchEstimate: "10–14 working days",
    specifications: [{ label: "Typical Contents", value: "Bag, Notebook, Pen" }],
    tags: ["events", "corporate-teams"],
  },
  // ── Promotional ──────────────────────────────────────────────────────
  {
    slug: "promotional-merchandise-kit",
    name: "Promotional Merchandise Kit",
    category: "promotional",
    description: "A mixed bundle of small-format promotional items for brand giveaways at scale — exact contents are confirmed in quotation.",
    material: "mixed",
    gsm: null,
    moq: 50,
    unit: "kit",
    dispatchEstimate: "10–14 working days",
    specifications: [{ label: "Format", value: "Mixed small-format items" }],
    tags: ["marketing-campaigns", "promotional"],
  },
  {
    slug: "event-essentials-kit",
    name: "Event Essentials Kit",
    category: "promotional",
    description: "A practical bundle for event staff and attendees — exact contents (lanyards, badges, bags) are confirmed in quotation.",
    material: "mixed",
    gsm: null,
    moq: 50,
    unit: "kit",
    dispatchEstimate: "10–14 working days",
    specifications: [{ label: "Format", value: "Mixed event items" }],
    tags: ["events"],
  },
];

module.exports = { NEW_PRODUCTS };
